<?php

namespace ContainerPkxW64u;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBoutiqueAdminControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BoutiqueAdminController' shared autowired service.
     *
     * @return \App\Controller\BoutiqueAdminController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'BoutiqueAdminController.php';

        $container->services['App\\Controller\\BoutiqueAdminController'] = $instance = new \App\Controller\BoutiqueAdminController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? self::get_ServiceLocator_ZyP9f7KService($container))->withContext('App\\Controller\\BoutiqueAdminController', $container));

        return $instance;
    }
}
