<?php

namespace ContainerPkxW64u;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCorsControlleronKernelResponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zi6SGfi.App\Controller\CorsController::onKernelResponse()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zi6SGfi.App\\Controller\\CorsController::onKernelResponse()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.zi6SGfi.Symfony\\Component\\HttpKernel\\Event\\ResponseEvent', NULL, 'Cannot autowire service ".service_locator.zi6SGfi": it references class "Symfony\\Component\\HttpKernel\\Event\\ResponseEvent" but no such service exists.'],
        ], [
            'event' => 'Symfony\\Component\\HttpKernel\\Event\\ResponseEvent',
        ]))->withContext('App\\Controller\\CorsController::onKernelResponse()', $container);
    }
}
