<?php

namespace ContainerPkxW64u;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResponseEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zi6SGfi.Symfony\Component\HttpKernel\Event\ResponseEvent' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Event\ResponseEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zi6SGfi": it references class "Symfony\\Component\\HttpKernel\\Event\\ResponseEvent" but no such service exists.');
    }
}
