<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPkxW64u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPkxW64u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPkxW64u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPkxW64u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPkxW64u\App_KernelDevDebugContainer([
    'container.build_hash' => 'PkxW64u',
    'container.build_id' => 'fdd186b9',
    'container.build_time' => 1750426764,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPkxW64u');
